### ISSUE TITLE
Custom component doesn't start properly

### ISSUE THREAD

**Issue by djmalin** [syssi/philipslight#34]
Hello @syssi i have Home Assistant 0.106.0b5 and this lamp Xiaomi Philips Smart LED Ball, so far everything works on version 105 so now the lamp stopped working and such an error appears

WARNING (MainThread) [homeassistant.loader] You are using a custom integration for xiaomi_miio_philipslight which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2020-02-26 07:27:11 ERROR (MainThread) [homeassistant.config] Platform error: light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 752, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 277, in get_platform
    f"{self.pkg_path}.{platform_name}"
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/xiaomi_miio_philipslight/light.py", line 11, in <module>
    from homeassistant.components.light import (
ImportError: cannot import name 'ATTR_ENTITY_ID' from 'homeassistant.components.light' (/usr/src/homeassistant/homeassistant/components/light/__init__.py)

**Comment by syssi** [comment]
This custom component needs some changes to be 0.106 compatible. Are you able to use the official component (xiaomi_miio). What's missing there?

**Comment by djmalin** [comment]
ok, it works on the official version, I did not know that there is official support :), everything is needed

**Comment by kooyeed** [comment]
I have the same problem, I have Home Assistant 0.116.0b4.

**Comment by TomDeSchutter** [comment]
I just tried implementing this myself to control a new bulb; looks like I'm encountering the same problem.
Running HA 0.117.0. I'm clueless.

Configuration invalid

Platform error light.xiaomi_miio_philipslight - cannot import name 'ATTR_ENTITY_ID' from 'homeassistant.components.light' (/usr/src/homeassistant/homeassistant/components/light/__init__.py)

**Comment by syssi** [comment]
I will care about. :-)

**Comment by syssi** [comment]
Fixed.

**Comment by TomDeSchutter** [comment]
As much as I admire the speed of your response, I'm afraid not.

Logger: homeassistant.components.light
Source: custom_components/xiaomi_miio_philipslight/light.py:175
Integration: Light (documentation, issues)
First occurred: 23:13:53 (1 occurrences)
Last logged: 23:13:53

Error while setting up xiaomi_miio_philipslight platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 197, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/xiaomi_miio_philipslight/light.py", line 175, in async_setup_platform
    light = PhilipsBulb(host, token)
NameError: name 'PhilipsBulb' is not defined

**Comment by syssi** [comment]
@TomDeSchutter Which Home Assistant version do you use? Please try the most recent version (0.117.1).

**Comment by syssi** [comment]
New HA versions respects the manifest.json and retrieves all requirements. In this case `python-miio`. This library provides the missing class. It looks like your HA instance doesn't provide this dependency.
