### ISSUE TITLE
philips.light.candle2: ERROR ON DEVICE UPDATE on HA Supervisor 2021.12.1

### ISSUE THREAD

**Issue by drafort** [syssi/philipslight#54]
current configuration:
- platform: xiaomi_miio_philipslight
  name: philips_light_kitchen
  host: 192....
  token: ....
  model: philips.light.candle2

Logger: homeassistant.components.light
Source: custom_components/xiaomi_miio_philipslight/light.py:552
Integration: Освещение (documentation, issues)
First occurred: 21:33:08 (1 occurrences)
Last logged: 21:33:08

xiaomi_miio_philipslight: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 684, in async_device_update
    await task
  File "/config/custom_components/xiaomi_miio_philipslight/light.py", line 533, in async_update
    self._color_temp = self.translate(
  File "/config/custom_components/xiaomi_miio_philipslight/light.py", line 552, in translate
    value_scaled = float(value - left_min) / float(left_span)
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'

**Comment by vramich** [comment]
exact the same issue after update  :(

**Comment by whitesabv** [comment]
У меня тоже самое.

**Comment by syssi** [comment]
Please update HA core to version 2021.12.2 and this custom component to version 1.4.6. This should fix the issue.

**Comment by vramich** [comment]
@syssi thx, it works!
