### ISSUE TITLE
Error setup device

### ISSUE THREAD

**Issue by cherniavsky94w** [syssi/philipslight#60]
Logger: homeassistant.components.light
Source: custom_components/xiaomi_miio_philipslight/light.py:556
Integration: Освітлення (documentation, issues)
First occurred: 12:22:53 (2 occurrences)
Last logged: 12:22:53

xiaomi_miio_philipslight: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 684, in async_device_update
    await task
  File "/config/custom_components/xiaomi_miio_philipslight/light.py", line 537, in async_update
    self._color_temp = self.translate(
  File "/config/custom_components/xiaomi_miio_philipslight/light.py", line 556, in translate
    value_scaled = float(value - left_min) / float(left_span)
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'

**Comment by syssi** [comment]
Please give it another try and re-open the issue if it's still present.
